export const DATA: "data";
export const EMPTY: "";
export const ID_MSG: "id: %ID\n";
export const ID_TOKEN: "%ID";
export const EVENT_MSG: "event: %EVENT\n";
export const EVENT_TOKEN: "%EVENT";
export const DATA_MSG: "data: %DATA\n\n";
export const DATA_TOKEN: "%DATA";
export const STRING: "string";
export const MESSAGE: "message";
export const NUMBER: "number";
export const PING: "ping";
export const INT_NEG_1: -1;
export const INT_0: 0;
export const INT_200: 200;
export const CONTENT_TYPE: "content-type";
export const TEXT_EVENT_STREAM: "text/event-stream";
export const CACHE_CONTROL: "cache-control";
export const NO_STORE_MAX_AGE_0: "no-store, max-age=0";
export const CONNECTION: "connection";
export const KEEP_ALIVE: "keep-alive";
export const CLOSE: "close";
